# Generated by Django 3.2 on 2022-08-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_building_test_testbuildingitem_building_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbuildingitem',
            name='building_test_id',
        ),
        migrations.DeleteModel(
            name='TestBuilding',
        ),
        migrations.DeleteModel(
            name='TestBuildingItem',
        ),
    ]
