# Generated by Django 3.2 on 2022-08-31 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_building_test_id_testbuildingitem_building_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbuildingitem',
            name='guid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
