# Generated by Django 3.2 on 2022-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_testbuilding_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbuilding',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testbuilding',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testbuildingitem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testbuildingitem',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
