# Generated by Django 3.2 on 2022-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220831_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbuilding',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='testbuildingitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
