# Generated by Django 3.2 on 2022-09-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220831_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbuilding',
            name='state',
            field=models.CharField(blank=True, choices=[('o', 'OPEN'), ('c', 'CLOSE'), ('l', 'LOST')], default='green', max_length=50, null=True),
        ),
    ]
