# Generated by Django 3.2 on 2022-09-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_testbuilding_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbuilding',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testbuilding',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'OPEN'), ('c', 'CLOSE'), ('l', 'LOST')], default='o', max_length=50, null=True),
        ),
    ]
