# Generated by Django 3.2 on 2022-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220907_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbuilding',
            name='status',
            field=models.CharField(choices=[('o', 'OPEN'), ('c', 'CLOSE'), ('l', 'LOST')], default='o', max_length=50),
        ),
    ]
